name : Feature CICD Development

on:
  push: 
      branches:
        - 'feature**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3

      - name: deploy
      run: echo "deploying on the feature branch"



      

